export const guns = [
    {id: 0, name: "SVA 545", conversion: false},
    {id: 1, name: "RAM-7", conversion: false},
    {id: 2, name: "MTZ-556", conversion: false},
    {id: 3, name: "Holger 556", conversion: false},
    {id: 4, name: "MCW", conversion: false},
    {id: 5, name: "DG-56", conversion: false},
    {id: 6, name: "FR 5.56", conversion: false},
    {id: 7, name: "TAQ-56", conversion: false},
    {id: 8, name: "M4", conversion: false},
    {id: 9, name: "STB 556", conversion: false},
    {id: 10, name: "Kastov 762", conversion: false},
    {id: 11, name: "M13B", conversion: false},
    {id: 12, name: "Chimera", conversion: false},
    {id: 13, name: "ISO Hemlock", conversion: false},
    {id: 14, name: "Tempus Razorback", conversion: false},
    {id: 15, name: "FR Avancer", conversion: false},
    {id: 16, name: "M13C", conversion: false},
    {id: 17, name: "TR-76 Geist", conversion: false},
    {id: 18, name: "Lachmann-556", conversion: false},
    {id: 19, name: "M16", conversion: false},
    {id: 20, name: "Kastov-74u", conversion: false},
    {id: 21, name: "Kastov 545", conversion: false},
    {id: 22, name: "BAS-B", conversion: false},
    {id: 23, name: "Sidewinder", conversion: false},
    {id: 24, name: "MTZ-762", conversion: false},
    {id: 25, name: "Lachmann-762", conversion: false},
    {id: 26, name: "Cronen Squall", conversion: false},
    {id: 27, name: "FTAC Recon", conversion: false},
    {id: 28, name: "TAQ-V", conversion: false},
    {id: 29, name: "SO-14", conversion: false},
    {id: 30, name: "Striker", conversion: false},
    {id: 31, name: "WSP Swarm", conversion: false},
    {id: 32, name: "AMR9", conversion: false},
    {id: 33, name: "WSP-9", conversion: false},
    {id: 34, name: "Rival-9", conversion: false},
    {id: 35, name: "Striker-9", conversion: false},
    {id: 36, name: "Lachmann Shroud", conversion: false},
    {id: 37, name: "ISO 9mm", conversion: false},
    {id: 38, name: "PDSW 528", conversion: false},
    {id: 39, name: "Vel 46", conversion: false},
    {id: 40, name: "Fennec 45", conversion: false},
    {id: 41, name: "BAS-P", conversion: false},
    {id: 42, name: "ISO 45", conversion: false},
    {id: 43, name: "Lachmann Sub", conversion: false},
    {id: 44, name: "FSS Hurricane", conversion: false},
    {id: 45, name: "MX9", conversion: false},
    {id: 46, name: "Minibak", conversion: false},
    {id: 47, name: "Vaznev-9K", conversion: false},
    {id: 48, name: "Lockwood 680", conversion: false},
    {id: 49, name: "Haymaker", conversion: false},
    {id: 50, name: "Riveter", conversion: false},
    {id: 51, name: "Lockwood 300", conversion: false},
    {id: 52, name: "Expedite 12", conversion: false},
    {id: 53, name: "Bryson 800", conversion: false},
    {id: 54, name: "KV Broadside", conversion: false},
    {id: 55, name: "MX Guardian", conversion: false},
    {id: 56, name: "Bryson 890", conversion: false},
    {id: 57, name: "Pulemyot 762", conversion: false},
    {id: 58, name: "DG-58 LSW", conversion: false},
    {id: 59, name: "TAQ Eradicator", conversion: false},
    {id: 60, name: "Bruen MK9", conversion: false},
    {id: 61, name: "Holger 26", conversion: false},
    {id: 62, name: "SAKIN MG38", conversion: false},
    {id: 63, name: "Raal MG", conversion: false},
    {id: 64, name: "556 Icarus", conversion: false},
    {id: 65, name: "Rapp H", conversion: false},
    {id: 66, name: "HCR 56", conversion: false},
    {id: 67, name: "RPK", conversion: false},
    {id: 68, name: "KVD Enforcer", conversion: false},
    {id: 69, name: "MCW 6.8", conversion: false},
    {id: 70, name: "DM56", conversion: false},
    {id: 71, name: "MTZ Interceptor", conversion: false},
    {id: 72, name: "EBR-14", conversion: false},
    {id: 73, name: "SP-R 208", conversion: false},
    {id: 74, name: "Lockwood Mk2", conversion: false},
    {id: 75, name: "Tempus Torrent", conversion: false},
    {id: 76, name: "Crossbow", conversion: false},
    {id: 77, name: "LM-S", conversion: false},
    {id: 78, name: "SA-B 50", conversion: false},
    {id: 79, name: "TAQ-M", conversion: false},
    {id: 80, name: "XRK Stalker", conversion: false},
    {id: 81, name: "Katt-AMR", conversion: false},
    {id: 82, name: "Longbow", conversion: false},
    {id: 83, name: "KV Inhibitor", conversion: false},
    {id: 84, name: "MCPR-300", conversion: false},
    {id: 85, name: "Signal 50", conversion: false},
    {id: 86, name: "Victus XMR", conversion: false},
    {id: 87, name: "FJX Imperium", conversion: false},
    {id: 88, name: "Carraack .300", conversion: false},
    {id: 89, name: "LA-B 300", conversion: false},
    {id: 90, name: "SP-X 80", conversion: false},
    {id: 91, name: "COR-45", conversion: false},
    {id: 92, name: "Renetti", conversion: false},
    {id: 93, name: "Tyr", conversion: false},
    {id: 94, name: "WSP Stinger", conversion: false},
    {id: 95, name: "P890", conversion: false},
    {id: 96, name: ".50 GS", conversion: false},
    {id: 97, name: "X12", conversion: false},
    {id: 98, name: "Basilisk", conversion: false},
    {id: 99, name: "FTAC Siege", conversion: false},
    {id: 100, name: "GS Magna", conversion: false},
    {id: 101, name: "9mm Daemon", conversion: false},
    {id: 102, name: "X13 Auto", conversion: false},
    {id: 103, name: "Stormender", conversion: false},
    {id: 104, name: "RGL-80", conversion: false},
    {id: 105, name: "PILA", conversion: false},
    {id: 106, name: "JOKR", conversion: false},
    {id: 107, name: "RPG-7", conversion: false},
    {id: 108, name: "Strela-P", conversion: false},
    {id: 109, name: "Riot Shield", conversion: false},
    {id: 110, name: "Gutter Knife", conversion: false},
    {id: 111, name: "Karambit", conversion: false},
    {id: 112, name: "Tonfa", conversion: false},
    {id: 113, name: "Combat Knife", conversion: false},
    {id: 114, name: "Dual Kodachis", conversion: false},
    {id: 115, name: "Dual Kamas", conversion: false},
    {id: 116, name: "Pickaxe", conversion: false},
    {id: 117, name: "JAK Raven MCW", conversion: true},
    {id: 118, name: "JAK Heretic MTZ-762", conversion: true},
    {id: 119, name: "Akimbo WSP Swarm", conversion: true},
    {id: 120, name: "Broodmother .45 WSP-9", conversion: true},
    {id: 121, name: "JAK Headhunter Rival-9", conversion: true},
    {id: 122, name: "JAK Annihilator Pulemyot 762", conversion: true},
    {id: 123, name: "JAK Nightshade DG-58 LSW", conversion: true},
    {id: 124, name: "MCW 6.8 Full Auto", conversion: true},
    {id: 125, name: "XRK IP-V2 COR-45", conversion: true},
    {id: 126, name: "JAK Ferocity Renetti", conversion: true},
    {id: 127, name: "JAK Beholder Tyr", conversion: true},
    {id: 128, name: "JAK Signal Burst Holger 556", conversion: true},
    {id: 129, name: "JAK Signal Burst DM56", conversion: true}
];